name: CI-Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  selenium:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - PY_VER: py38
            python-version: 3.8
          - PY_VER: py39
            python-version: 3.9
          - PY_VER: py310
            python-version: "3.10"
          - PY_VER: py311
            python-version: 3.11
          - PY_VER: py312
            python-version: "3.12"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install test dependencies
        run: pip install tox

      - name: Set env
        run: echo "DISPLAY=:99.0" >> $GITHUB_ENV

      - name: Run tests for windows-only drivers
        run: |
          tox -e tests_windows_selenium -- -n 4 tests/test_webdriver.py tests/test_popups.py tests/test_webdriver_edge_chromium.py;
